src/scutes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpRequest
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView


from processing.views import (
    About,
    BatchDetailsView,
    BatchList,
    batch_clean,
    batch_convert_and_export,
    batch_mark_redaction,
    Dashboard,
    edit_batch,
    edit_batch_submit,
    FinalizeBatchView,
    Index,
    ItemListView,
    ItemUpdateView,
    protected_media,
)


# Custom 400, 403, 404, and 500 pages
handler400 = 'processing.views.error_400'
handler403 = 'processing.views.error_403'
handler404 = 'processing.views.error_404'
handler500 = 'processing.views.error_500'


urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('about/', About.as_view(), name='about'),
    path('batchlist/', BatchList.as_view(), name='batchlist'),
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('', Index.as_view(), name='index'),
    path('itemlist/<int:batch>/', ItemListView.as_view(), name='itemlistview'),
    path('finalizebatch/<int:pk>/', FinalizeBatchView.as_view(), name='finalizebatchview'),
    path('batch_convert_and_export/', batch_convert_and_export, name='batch_convert_and_export'),
    path('batchdetails/<int:pk>/', BatchDetailsView.as_view(), name='batchdetailsview'),
    path('itemview/<int:pk>/', ItemUpdateView.as_view(), name='itemupdateview'),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('media/<str:directory>/<str:filename>', protected_media),
    re_path(r'saml2/', include('djangosaml2.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

htmx_urlpatterns = [
    path('<int:batch_pk>/edit_batch/', edit_batch, name='edit_batch'),
    path('<int:batch_pk>/edit_batch_submit/', edit_batch_submit, name='edit_batch_submit'),
    path('batch_clean/', batch_clean, name='batch_clean'),
    path('batch_mark_redaction/', batch_mark_redaction, name='batch_mark_redaction'),
]

urlpatterns += htmx_urlpatterns


def get_navigation_links(request: HttpRequest):
    if request.user.is_authenticated:
        authenticated_links = {
            'dashboard': 'Dashboard',
            'batchlist': 'Batch List',
            '': f'Logged in as {request.user.username}',
            'saml2_logout': 'Log Out',
        }
        if request.user.is_superuser:
            superuser_links = {
                'admin:index': 'Admin',
            }
        else:
            superuser_links = {}
        links = {**superuser_links, **authenticated_links}
        return links
    else:
        return {'saml2_login': 'Log In'}


def get_footer_links(request: HttpRequest):
    if request.user.is_authenticated:
        authenticated_links = {
            'about': 'About',
        }
        if request.user.is_superuser:
            superuser_links = {}
        else:
            superuser_links = {}
        links = {**superuser_links, **authenticated_links}
        return links
    else:
        return {'saml2_login': 'Log In'}

src/processing/models.py
import re

from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass


class Batch(models.Model):
    class Meta:
        verbose_name_plural = 'Batches'

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    assigned_to = models.ForeignKey('user', on_delete=models.SET_NULL, blank=True, null=True)
    notes = models.TextField(max_length=1000, blank=True, null=True)
    datetime_added = models.DateTimeField(auto_now=True, null=True)
    last_export = models.DateTimeField(null=True)
    export_zip = models.FileField(upload_to='export', null=True)

    @property
    def not_started_item_count(self):
        return self.item_set.filter(review_status__contains=0).count()

    @property
    def in_progress_total_item_count(self):
        return self.item_set.filter(review_status__contains=1).count()

    @property
    def complete_total_item_count(self):
        return self.item_set.filter(review_status__contains=2).count()


class File(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    content_type = models.TextField(blank=True, null=True)
    content_disposition = models.TextField(blank=True, null=True)
    content_id = models.TextField(blank=True, null=True)
    disposition = models.CharField(max_length=255, blank=True, null=True)
    file = models.FileField(upload_to='files')
    item = models.ForeignKey('Item', on_delete=models.CASCADE)

    @property
    def file_type(self):
        file_type = re.split(';', self.content_type)[0]
        if file_type == 'image/jpeg':
            return 'image'
        if file_type == 'image/jpg':
            return 'image'
        if file_type == 'image/png':
            return 'image'
        if file_type == 'application/pdf':
            return 'pdf'
        if file_type == 'audio/mpeg':
            return 'audio'
        return 'other'


class Item(models.Model):
    class Status(models.IntegerChoices):
        INACTIVE = 0, 'Not Started'
        ACTIVE = 1, 'In Progress'
        COMPLETE = 2, 'Complete'

    id = models.AutoField(primary_key=True)
    date = models.DateTimeField(blank=True)
    reporter = models.CharField(max_length=255, blank=True)
    title = models.CharField(max_length=255, blank=True)
    pool_report = models.BooleanField(null=False)
    publish = models.BooleanField(null=False)
    off_the_record = models.BooleanField(null=False)
    review_status = models.SmallIntegerField(
        choices=Status.choices, blank=False, default='Unspecified', verbose_name='Editorial Review'
    )
    notes = models.TextField(max_length=1000, blank=True, null=True)
    body_original = models.TextField(blank=True, null=True)
    body_clean = models.TextField(blank=True, null=True)
    body_redact = models.TextField(blank=True, null=True)
    body_final = models.TextField(blank=True, null=True)
    last_modified = models.DateTimeField(auto_now=True, null=True)
    batch = models.ForeignKey(
        'Batch',
        on_delete=models.CASCADE,
    )

    @property
    def attachment_count(self):
        return self.file_set.filter(disposition__contains='attachment').count

    @property
    def inline_count(self):
        return self.file_set.filter(disposition__contains='inline').count

    @property
    def external_count(self):
        return self.file_set.filter(disposition__contains='external').count

src/processing/views.py
from itertools import count
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count, Q
from django.http import FileResponse, HttpResponseForbidden, HttpResponseRedirect
from django.http.response import StreamingHttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, UpdateView
from django.views.generic.base import TemplateView

import logging
import pandas as pd
import pickle
import plotly.express as px

from base64 import b64encode, b64decode

from .filters import BatchFilter, ItemFilter
from .forms import BatchDetailForm, BatchForm, ItemUpdateForm
from .models import Batch, Item
from processing.common.convert_and_export import convert_and_export
from processing.common.clean import rerun_clean
from processing.common.mark_redaction import rerun_mark_redaction

logger = logging.getLogger(__name__)

LIST_PAGINATE_BY = 20


class About(TemplateView):
    template_name = 'about.html'

    def test_func(self):
        return self.request.user.is_staff


class Index(TemplateView):
    template_name = 'index.html'


class Dashboard(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Batch
    context_object_name = 'batch_list'
    template_name = 'dashboard.html'

    def test_func(self):
        return self.request.user.is_staff

    def user_name(self):
        user_name = self.request.user.username
        return user_name

    def get_queryset(self):
        queryset = Batch.objects.all().order_by('name').filter(assigned_to=self.request.user.id)
        return queryset

    def review_status_for_each_batch_chart(self):
        entries = Batch.objects.all().order_by('name')
        column_names = [field.name for field in Batch._meta.get_fields()]

        df = pd.DataFrame(columns=column_names)

        for element in entries:
            new_entry = {
                'name': element.name,
                'Not Started': element.not_started_item_count,
                'In Progress': element.in_progress_total_item_count,
                'Complete': element.complete_total_item_count,
            }
            df = df._append(new_entry, ignore_index=True)

        fig = px.bar(
            df,
            x='name',
            y=['Not Started', 'In Progress', 'Complete'],
            title='Review Status For Each Batch',
            text_auto=True,
            color_discrete_sequence=['red', 'yellow', 'green'],
        )
        fig.update_layout(
            xaxis={'type': 'category'},
            xaxis_title='Batch Name',
            yaxis_title='Number of Items',
            legend_title='Review Status',
        )

        review_status_for_each_batch_chart = fig.to_html()
        return review_status_for_each_batch_chart

    def total_item_count(self):
        total_item_count = Item.objects.all().count()
        return total_item_count

    def total_not_started_item_count(self):
        total_not_started_item_count = Item.objects.all().filter(review_status=0).count()
        return total_not_started_item_count

    def total_in_progress_item_count(self):
        total_in_progress_item_count = Item.objects.filter(review_status=1).count()
        return total_in_progress_item_count

    def total_complete_item_count(self):
        total_complete_item_count = Item.objects.filter(review_status=2).count()
        return total_complete_item_count

    def total_batch_count(self):
        total_batch_count = Batch.objects.all().count()
        return total_batch_count

    def batch_not_started(self):
        batch = Batch.objects.all()

        batch_not_started = []
        for batch in Batch.objects.prefetch_related('item_set').all():
            if batch.item_set.filter(review_status__contains=0).count() == batch.item_set.count():
                batch_not_started.append(batch)

        batch_not_started = len(batch_not_started)
        return batch_not_started

    def batch_in_progress(self):
        batch = Batch.objects.all()

        batch_in_progress = []
        for batch in Batch.objects.prefetch_related('item_set').all():
            if batch.item_set.filter(review_status__contains=2).count() != batch.item_set.count():
                batch_in_progress.append(batch)
            elif batch.item_set.filter(review_status__contains=1).exists():
                batch_in_progress.append(batch)

        batch_not_started = []
        for batch in Batch.objects.prefetch_related('item_set').all():
            if batch.item_set.filter(review_status__contains=0).count() == batch.item_set.count():
                batch_not_started.append(batch)

        batch_in_progress = len(batch_in_progress) - len(batch_not_started)
        return batch_in_progress

    def batch_complete(self):
        batches = Batch.objects.all()

        batch_complete = []
        for batch in batches:
            if batch.item_set.filter(review_status__contains=2).count() == batch.item_set.count():
                batch_complete.append(batch)

        batch_complete = len(batch_complete)
        return batch_complete

    def reporter_list(self):
        reporter_list = (
            Item.objects.values('reporter')
            .annotate(items=Count('reporter'))
            .annotate(publish=Count('publish', filter=Q(publish=1)))
        )
        return reporter_list

    def reporter_count(self):
        reporter_count = Item.objects.values('reporter').distinct().count()
        return reporter_count

    def publish_total(self):
        publish_total = Item.objects.values('publish').filter(publish=1).count()
        return publish_total

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update(
            {
                'user_name': self.user_name,
                'review_status_for_each_batch_chart': self.review_status_for_each_batch_chart,
                'total_item_count': self.total_item_count,
                'total_not_started_item_count': self.total_not_started_item_count,
                'total_in_progress_item_count': self.total_in_progress_item_count,
                'total_complete_item_count': self.total_complete_item_count,
                'total_batch_count': self.total_batch_count,
                'batch_not_started': self.batch_not_started,
                'batch_in_progress': self.batch_in_progress,
                'batch_complete': self.batch_complete,
                'reporter_list': self.reporter_list,
                'reporter_count': self.reporter_count,
                'publish_total': self.publish_total,
            }
        )
        return context


class BatchList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Batch
    context_object_name = 'batch_list'
    template_name = 'batch_list.html'
    paginate_by = LIST_PAGINATE_BY

    def get_template_names(self, *args, **kwargs):
        if self.request.htmx:
            return 'partials/batch_list_results.html'
        return self.template_name

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = BatchFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super(BatchList, self).get_context_data(**kwargs)
        query_params = self.request.GET.copy()
        if 'page' in query_params:
            del query_params['page']

        context.update(
            {
                'query_params': query_params.urlencode(),
                'form': self.filterset.form,
                'paginate_by': self.paginate_by,
            }
        )
        return context


def edit_batch(request, batch_pk):
    batch = Batch.objects.get(pk=batch_pk)
    context = {}
    context['batch'] = batch
    context['form'] = BatchForm(
        initial={
            'assigned_to': batch.assigned_to,
        }
    )
    return render(request, 'partials/edit_batch.html', context)


def edit_batch_submit(request, batch_pk):
    context = {}
    batch = Batch.objects.get(pk=batch_pk)
    context['batch'] = batch
    if request.method == 'POST':
        form = BatchForm(request.POST, instance=batch)
        if form.is_valid():
            form.save()
        else:
            return render(request, 'partials/edit_batch.html', context)
    return render(request, 'partials/batch_list_results_row_assigned_to.html', context)


class ItemListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Item
    context_object_name = 'item_list'
    template_name = 'item_list.html'
    paginate_by = LIST_PAGINATE_BY

    def get_template_names(self, *args, **kwargs):
        if self.request.htmx:
            return 'partials/item_list_results.html'
        return self.template_name

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):
        queryset = Item.objects.filter(batch=self.request.resolver_match.kwargs['batch']).order_by('id')
        self.filterset = ItemFilter(self.request.GET, queryset=queryset)

        # Session keys
        key = 'my_qs'
        key_url = 'key_url'

        # Django wants datatypes to be JSON serializable. Byte objects need to be encoded/decoded
        self.request.session[key] = b64encode(pickle.dumps(self.filterset.qs.query)).decode('ascii')

        self.request.session[key_url] = self.request.GET

        return self.filterset.qs

    def item_list_batch(self, **kwargs):
        item_list_batch = self.request.resolver_match.kwargs['batch']
        return item_list_batch

    def item_list_batch_name(self, **kwargs):
        batch_id = self.request.resolver_match.kwargs['batch']
        item_list_batch_name = Batch.objects.get(pk=batch_id).name

src/processing/templates/partials/batch_list_results.html
{% for batch in batch_list %}

{% if page_obj.has_next and forloop.last %}
<tr hx-get="{% url 'batchlist' %}?{{ query_params }}&page={{ page_obj.next_page_number }}" hx-trigger="intersect once"
    hx-swap="afterend" hx-push-url="true">
    {% else %}
<tr>
    {% endif %}

    {% include 'partials/batch_list_results_row.html' %}
</tr>

{% endfor %}
<script>
    htmx.on("htmx:load", function (evt) {
        document.querySelector(".pagination").style.display = "none";
    });
</script>

src/processing/templates/partials/batch_list_results_row.html
<td>{{ batch.id }}</td>
<td>{{ batch.name }}</td>
<td>{% include 'partials/batch_list_results_row_assigned_to.html' %}</td>
<td>{{ batch.last_export|date:"M d, Y H:i e" }}</td>
<td><a class="btn btn-info btn-sm" href="{% url 'itemlistview' batch.id %}">Open</a></td>
<td><a class="btn btn-info btn-sm" href="{% url 'batchdetailsview' batch.id %}">Details</a></td>
<td><a class="btn btn-info btn-sm" href="{% url 'finalizebatchview' batch.id %}">Convert for Export</a></td>
<td>
    {% if batch.export_zip %}
    <a class="btn btn-info btn-sm" href="{{ batch.export_zip.url }}">
        <svg class="bi-download" width="16" height="16">
            <use xlink:href="#download">
        </svg>
        Download Batch
        <span class="badge bg-light text-dark">{{ batch.export_zip.size|filesizeformat }}</span>
    </a>
    {% endif %}
</td>

<script>
    htmx.on("htmx:load", function (evt) {
        document.querySelector(".pagination").style.display = "none";
    });
</script>

src/processing/templates/partials/batch_list_results_row_assigned_to.html
{{ batch.assigned_to|default_if_none:"-------" }}
<button class='btn' hx-get="{% url 'edit_batch' batch.pk %}" hx-target="closest td" hx-swap="innerHTML">
    <svg class="bi-pencil" width="16" height="16">
        <use xlink:href="#pencil">
    </svg>
</button>

src/processing/templates/partials/edit_batch.html
{% csrf_token %}
{{ form.assigned_to }}
{{ form.assigned_to.errors }}
<a href="#" hx-post="{% url 'edit_batch_submit' batch.pk %}" hx-target="closest td" hx-swap="innerHTML"
    hx-include="closest td" class="text-secondary">
    <svg class="bi-check" width="16" height="16">
        <use xlink:href="#checkmark" />
    </svg>
</a>
<a href="#" hx-get="{% url 'edit_batch_submit' batch.pk %}" hx-target="closest td" hx-swap="innerHTML"
    class="text-secondary">
    <svg class="bi-x" width="16" height="16">
        <use xlink:href=" #cancel" />
    </svg>
</a>

src/processing/templates/partials/item_attachment.html
<!-- Attachments -->

{% if attachment_count is not 0 %}
<h6>{{ attachment_count }} Attachment{{ attachment_count|pluralize }}</h6>
{% endif %}

{% for file in object.file_set.all %}
{% if file.disposition == 'attachment' %}
{% if file.file_type == 'image' %}
<!-- Stretched attachment link trigger modal -->
<div class="card" style="width: 18rem;">
    <img src="{{ file.file.url }}" class="card-img-top" alt="...">
    <div class="card-body">
        <a href="#" class="stretched-link" data-bs-toggle="modal" data-bs-target="#Modal{{ file.id }}">
            {{ file.name }}
        </a>
    </div>
</div>
<!-- Modal for attachments -->
<div class="modal fade" id="Modal{{ file.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Name: {{ file.name }}
                </h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <img src="{{ file.file.url }}" alt="image" style="width:100%">
                <br><br>
                <button type="button" class="btn btn-light">
                    <a href="{{ file.file.url }}" target="_blank" rel="noopener noreferrer">
                        <svg class="bi-download" width="16" height="16">
                            <use xlink:href="#download">
                        </svg>
                    </a>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<br>
{% elif file.file_type == 'pdf' %}
<div class="card" style="width: 18rem;">
    <div class="card-header">
        PDF
    </div>
    <div class="card-body">
        <p class="fw-medium">{{ file.name }}</p>
        <p class="fw-lighter">{{ file.file.size|filesizeformat }}</p>
        <button type="button" class="btn btn-light">
            <a href="{{ file.file.url }}" target="_blank" rel="noopener noreferrer">
                <svg class="bi-download" width="16" height="16">
                    <use xlink:href="#download">
                </svg>
            </a>
        </button>
    </div>
</div>
<br>
{% elif file.file_type == 'audio' %}
<div class="card" style="width: 18rem;">
    <div class="card-header">
        Audio
    </div>
    <div class="card-body">
        <p class="fw-medium">{{ file.name }}</p>
        <p class="fw-lighter">{{ file.file.size|filesizeformat }}</p>
        <button type="button" class="btn btn-light">
            <a href="{{ file.file.url }}" target="_blank" rel="noopener noreferrer">
                <svg class="bi-download" width="16" height="16">
                    <use xlink:href="#download">
                </svg>
            </a>
        </button>
    </div>
</div>
<br>
{% else %}
<div class="card" style="width: 18rem;">
    <div class="card-header">
        File
    </div>
    <div class="card-body">
        <p class="fw-medium">{{ file.name }}</p>
        <p class="fw-lighter">{{ file.file.size|filesizeformat }}</p>
        <button type="button" class="btn btn-light">
            <a href="{{ file.file.url }}" target="_blank" rel="noopener noreferrer">
                <svg class="bi-download" width="16" height="16">
                    <use xlink:href="#download">
                </svg>
            </a>
        </button>
    </div>
</div>

{% endif %}
{% endif %}
{% endfor %}

src/processing/templates/partials/item_external.html
<!-- external -->
{% if external_count is not 0 %}
<h6>{{ external_count }} External{{ external_count|pluralize }}</h6>
{% endif %}

{% for file in object.file_set.all %}
{% if file.disposition == 'external' %}
<div class="card" style="width: 18rem;">
    <div class="card-header">
        {{ file.disposition|capfirst }} - {{ file.file_type|capfirst }}
    </div>
    <div class="card-body">
        <img src="{{ file.file.url }}" alt="image" style="width:100%">
        <p class="fw-medium">{{ file.name }}</p>
        <p class="fw-lighter">{{ file.file.size|filesizeformat }}</p>
        <button type="button" class="btn btn-light">
            <a href="{{ file.file.url }}" target="_blank" rel="noopener noreferrer">
                <svg class="bi-download" width="16" height="16">
                    <use xlink:href="#download">
                </svg>
            </a>
        </button>
    </div>
</div>
<br>
{% endif %}
{% endfor %}

src/processing/templates/partials/item_inline.html
<!-- Inline -->
{% if inline_count is not 0 %}
<h6>{{ inline_count }} Inline{{ inline_count|pluralize }}</h6>
{% endif %}

{% for file in object.file_set.all %}
{% if file.disposition == 'inline' %}
<div class="card" style="width: 18rem;">
    <div class="card-header">
        {{ file.disposition|capfirst }} - {{ file.file_type|capfirst }}
    </div>
    <div class="card-body">
        <p class="fw-medium">{{ file.name }}</p>
        <p class="fw-lighter">{{ file.file.size|filesizeformat }}</p>
        <button type="button" class="btn btn-light">
            <a href="{{ file.file.url }}" target="_blank" rel="noopener noreferrer">
                <svg class="bi-download" width="16" height="16">
                    <use xlink:href="#download">
                </svg>
            </a>
        </button>
    </div>
</div>
<br>
{% endif %}
{% endfor %}

src/processing/templates/partials/item_list_results.html
{% for item in item_list %}

{% if page_obj.has_next and forloop.last %}
<tr hx-get="{% url 'itemlistview' item_list_batch %}?{{ query_params }}&page={{ page_obj.next_page_number }}"
    hx-trigger="intersect once" hx-swap="afterend" hx-push-url="true">
    {% else %}
<tr>
    {% endif %}

    <td>{{ item.id }}</td>
    <td>{{ item.date|date:"M d, Y H:i e" }}</td>
    <td>{{ item.reporter }}</td>
    <td>{{ item.title|truncatechars:40 }}</td>
    <td>{{ item.publish }}</td>
    <td>{{ item.pool_report }}</td>
    <td>{{ item.off_the_record }}</td>
    <td class="{% if item.get_review_status_display == 'Complete' %} text-success 
                            {% elif item.get_review_status_display == 'In Progress' %} text-warning 
                            {% else %} text-danger 
                            {% endif %}">
        {{ item.get_review_status_display }}
    </td>
    <td><a class="btn btn-info btn-sm" href="{% url 'itemupdateview' item.id %}">Open</a>
    </td>
</tr>

{% endfor %}
<script>
    htmx.on("htmx:load", function (evt) {
        document.querySelector(".pagination").style.display = "none";
    });
</script>

src/processing/templates/partials/release_notes.html
<div class="row mt-5 mb-5 justify-content-center">
    <div class="col-md-11">
        <hr class="border border-secondary border-3 opacity-75">
        <h2>Release Notes</h2>
        <hr>

        <h3>1.1.1</h3>
        <h4>Improvements</h4>
        <ul>
            <li>Added About page</li>
            <li>Added Dashboard page with batch statistics and quick link to assigned batches</li>
            <li>Added Batch Detail page</li>
        </ul>

        <hr>

        <h3>1.1.0</h3>
        <h4>Improvements</h4>
        <ul>
            <li>Added "assigned to" to Batch List</li>
            <li>Added ordering filter to Batch List</li>
            <li>Added batch statitics to Item List</li>
            <li>Improved Item View body views</li>
            <li>Improved phone number redaction</li>
        </ul>

        <hr>

        <h3>1.0.0 MVP Testing Milestone 4</h3>
        <h4>Improvements</h4>
        <ul>
            <li>Added Single Sign On</li>
            <li>Added "pool_report" and "off-the-record" filters to Item List</li>
            <li>Added finalize redactions and export functions</li>
        </ul>

        <hr>

        <h3>1.0.0 MVP Testing Milestone 3</h3>
        <h4>Improvements</h4>
        <ul>
            <li>Item View</li>
            <ul>
                <li>On first save, change editorial review to 'In progress'</li>
            </ul>
            <li>Attachments, Inlines and External Images</li>
            <ul>
                <li>Importing of files</li>
                <li>Display of files in Item View</li>
            </ul>
            <li>Index Page</li>
            <ul>
                <li>Added login link</li>
            </ul>
            <li>For Development</li>
            <ul>
                <li>Added Debug Toolbar</li>
            </ul>
        </ul>

        <hr>

        <h3>1.0.0 MVP Testing Milestone 2</h3>
        <h4>Improvements</h4>
        <ul>
            <li>Item View</li>
            <ul>
                <li>Item 'Previous Item' and 'Next Item' buttons use applied filters</li>
                <li>'Save & Next' button uses applied filters</li>
                <li>Added navigation to Item List with applied filters and without applied filters</li>
                <li>Moved Item 'Save", 'Save & Next', and 'Reset' buttons</li>
            </ul>
            <li>Item List</li>
            <ul>
                <li>Added filtering for Publish column</li>
                <li>Editorial Review column has stoplight colors for better visual clarity</li>
            </ul>
            <li> Batch List</li>
            <ul>
                <li>Disabled 'Assigned to' column</li>
            </ul>
            <li> Index Page</li>
            <ul>
                <li>Improved layout and style</li>
            </ul>
            <li>Auto-redaction</li>
            <ul>
                <li>Phone number auto-redaction no longer removes numbers from redacted strikethrough</li>
                <li>Email address auto-redaction removes link</li>
            </ul>
        </ul>

        <hr>

        <h3>1.0.0 MVP Testing Milestone 1</h3>
        <h4>Select features</h4>
        <ul>
            <li>Batch list</li>
            <li>Item list</li>
            <li>Item view</li>
            <li>Authentication (temporary) for security</li>
            <li>Full email pre-processing via commands</li>
        </ul>

    </div>
</div>